# Generated by Django 2.1.2 on 2018-10-15 22:20

import django.core.validators
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter phone number with only numbers (no dashes).', regex='^\\d{10,15}$')])),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', localflavor.us.models.USZipCodeField(max_length=10)),
                ('zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Zipcode must be five digits.', regex='^\\d{5}$')])),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('country', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Resellers',
            },
        ),
    ]
