# Generated by Django 2.1.2 on 2018-10-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellers',
            name='country',
        ),
    ]
