# Generated by Django 2.1.2 on 2018-10-16 16:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181015_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
