# Generated by Django 2.1.2 on 2018-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181016_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellers',
            name='latitude',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resellers',
            name='longitude',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
