# Generated by Django 2.1.2 on 2018-10-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181016_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellers',
            name='comments',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
