# Generated by Django 2.1.2 on 2018-10-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
