# Generated by Django 2.1.2 on 2018-10-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_uploadfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
    ]
